// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcnJiA2Vq6bDcOuU99z6CzZB_8HB8rZtU',
    appId: '1:832144918546:web:21eaa72848a72e1f1530cb',
    messagingSenderId: '832144918546',
    projectId: 'ecommerce-task-efdf8',
    authDomain: 'ecommerce-task-efdf8.firebaseapp.com',
    storageBucket: 'ecommerce-task-efdf8.firebasestorage.app',
    measurementId: 'G-YRY5FV1LNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpJnNBDwFNgbg9zvR8CD0RYDxp-X0rf-0',
    appId: '1:832144918546:android:eff87404c215866b1530cb',
    messagingSenderId: '832144918546',
    projectId: 'ecommerce-task-efdf8',
    storageBucket: 'ecommerce-task-efdf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLsTXLwcI4ze92eCXGK_xbKccJp9ycec',
    appId: '1:832144918546:ios:dea4068c9d1c78a41530cb',
    messagingSenderId: '832144918546',
    projectId: 'ecommerce-task-efdf8',
    storageBucket: 'ecommerce-task-efdf8.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLsTXLwcI4ze92eCXGK_xbKccJp9ycec',
    appId: '1:832144918546:ios:dea4068c9d1c78a41530cb',
    messagingSenderId: '832144918546',
    projectId: 'ecommerce-task-efdf8',
    storageBucket: 'ecommerce-task-efdf8.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcnJiA2Vq6bDcOuU99z6CzZB_8HB8rZtU',
    appId: '1:832144918546:web:8c5fdb4e645a1c621530cb',
    messagingSenderId: '832144918546',
    projectId: 'ecommerce-task-efdf8',
    authDomain: 'ecommerce-task-efdf8.firebaseapp.com',
    storageBucket: 'ecommerce-task-efdf8.firebasestorage.app',
    measurementId: 'G-84F9HN190J',
  );

}